import {expect,it} from 'vitest';
import {createState,resolveDay,resolveNight} from '../../src/game/domain/rules.js';
import {GameConfig} from '../../src/shared/config.js';
import {openRequest} from '../../src/game/domain/requests.js';
import {buildObservation} from '../../src/game/runtime/observation.js';
import {Event} from '../../src/shared/events.js';
import {project} from '../../src/shared/presentation/project.js';
import {foldEvents} from '../../src/shared/presentation/fold.js';
import {knownRole} from '../../src/viewer/known-role.js';
import {stageSummary} from '../../src/viewer/stage-summary.js';
const seed='000102030405060708090a0b0c0d0e0f';
it.each(['vote','wolf'] as const)('reveals only the victim publicly after %s death, including to agents and UI',cause=>{
 const s=createState(seed),victim=cause==='vote'?1:2;
 const role=s.seats[victim]!.role,faction=s.seats[victim]!.faction;
 const results=cause==='vote'?resolveDay(s,s.seats.map(p=>({slot:p.slot,target:victim}))):resolveNight(s,[{slot:1,actions:[{ability:'kill',target:victim,killer:1}]}]);
 const death=results.find(e=>e.kind==='elimination')!;
 expect(death).toMatchObject({slot:victim,role,faction});
 const journal=[Event.parse({schema:'wcw.events/1',seq:1,day:1,phase:cause==='vote'?'vote':'night',audience:{kind:'public'},reveal:'public',payload:death})];
 const visible=project(journal,'public');
 expect(foldEvents(visible).roles).toEqual({[victim]:role});
 expect(knownRole({self:{slot:0,role:'sheep'},teammates:[],events:visible},victim)).toBe(role);
 expect(knownRole({self:{slot:0,role:'sheep'},teammates:[],events:visible},3)).toBeNull();
 const c=GameConfig.parse({tokens:s.seats.map(p=>`token-${p.slot}`),players:s.seats.map(p=>({name:`Player ${p.slot}`}))});
 const p=openRequest({slot:0,episodeId:'e',requestId:'r',observationId:'o',deadline:1000,request:{kind:'bid',window:0,maxCharacters:480}});
 const o=buildObservation(s,c,journal,p,'day',0);
 expect(o.transcript).toContainEqual(expect.objectContaining({payload:death}));
 expect(o.roster.every(p=>!('role' in p))).toBe(true);
 const longJournal=[...journal,...Array.from({length:140},(_,i)=>Event.parse({schema:'wcw.events/1',seq:i+2,day:1,phase:'day',audience:{kind:'public'},reveal:'public',payload:{kind:'speech',speech:{slot:0,text:'Discussion',replyTo:null,accusation:null}}}))];
 const long=buildObservation(s,c,longJournal,p,'day',0);
 expect(long.transcript).toHaveLength(128);expect(long.transcriptTruncated).toBe(true);
 expect(long.transcript[0]!.payload).toEqual(death);
 const events=[...visible,...results.filter(e=>e.kind==='ballots'||e.kind==='night_resolved').map(payload=>({day:1,payload}))];
 expect(stageSummary({period:cause==='vote'?'dusk':'dawn',day:cause==='vote'?1:2,events,roster:c.players})?.description).toContain(faction==='wolf'?'Wolves':'Town');
});
